
# Site settings

title: ComputePods Projects
email: your-email@example.com
description: An overview for the ComputePods project
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll
paginate:            5
permalink:           pretty
version: 0.0.1

github:
  repo: https://github.com/computePods/computePods.github.io
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Build settings
plugins:
  - jekyll-feed
  #- jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
